[package]
name = "passify"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
anyhow = "1"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
store = { path = "lib/store" }
