[package]
name = "passify"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
